# Generated by Django 3.1.14 on 2023-03-24 10:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20230324_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='pokemon_entities.pokemon', verbose_name='Из кого появился'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 10, 57, 22, 209009, tzinfo=utc), null=True, verbose_name='Появиться в'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 10, 57, 22, 209009, tzinfo=utc), null=True, verbose_name='Исчезнет в'),
        ),
    ]
